### PR TITLE
🙈 Add Gemfile.lock to gitignore

### PR DESCRIPTION
**Pull request by tylerwillingham**
When reconciling dependencies in a project setting this lockfile is
already ignored. When developers are working on and contributing to
`fake_idp`, the specific dependency lock shouldn't matter - only the
version constraints set in the gemspec.

Ignoring the lockfile and allowing developers to use different
dependencies within the gemspec constraints better simulates the gem's
use in the wild and might enable catching dependency issues sooner

### CODE REVIEW

**Comment by tylerwillingham** [comment]
This should also resolve the dependabot PRs

**Review by k-peek — APPROVED** [review]
This looks good to me -- thanks for the contribution!

**Review by shashank-date — APPROVED** [review]
LGTM

**Review by ernestns — APPROVED** [review]
Thanks for the changes 👍

**Comment by ernestns** [comment]
@tylerwillingham when you have a moment, could you enable "Allow edits by maintainers" 🙏 
image

**Comment by tylerwillingham** [comment]
@ernestns @RodCardenas done 👍

**Comment by RodCardenas** [comment]
Addressed in https://github.com/healthify/fake_idp/pull/64

**Pull request closed without merging**
